spring.application.name=violentometro-backend
server.port=8082

# Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/violentometro
spring.datasource.username=postgres
spring.datasource.password=03754

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion del pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

jwt.secret=istr_violentometro_secret_key_2024_bienestar_institucional
jwt.expiration=86400000

app.encryption.secret-key=MiClaveSecreta12345678901234AB55